# kmeans++ + swin-T + BiFPN + nc3
# 验证BiFPN的可用性
backbone:
  type: SwinTransformer
  pretrain_img_size: 384
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 6
  drop_path_rate: 0.2
  version: swin-T
neck:
  type: BiFPN
head:
  nc: 3
  stride: [8.0, 16.0, 32.0]
  anchors:
    - [10,5, 18,8, 19,9]  # P3/8
    - [21,10, 25,11, 37,15]  # P4/16
    - [39,17, 49,19, 65,22]  # P5/32