# kmeans++ + swin-T + BiFPN + 4head + nc3
backbone:
  type: SwinTransformer4
  pretrain_img_size: 384
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 6
  drop_path_rate: 0.2
  version: swin-T
neck:
  type: BiFPN4
  num_channels: 256
  depths: 4
head:
  nc: 3
  stride: [4.0, 8.0, 16.0, 32.0]
  anchors:
    - [9,4, 3,9, 5,11]  # P2/4
    - [10,5, 18,8, 19,9]  # P3/8
    - [21,10, 25,11, 37,15]  # P4/16
    - [39,17, 49,19, 65,22]  # P5/32