# m + kmeans
backbone:
  type: YOLOv5
  version: m # x, m, l ,x
  focus: True
  with_C3TR: False
head:
  nc: 2
  stride: [8.0, 16.0, 32.0]
  anchors:
    - [10,5, 18,8, 19,9]  # P3/8
    - [21,10, 25,11, 37,15]  # P4/16
    - [39,17, 49,19, 65,22]  # P5/32