# kmeans++ + swin-S
backbone:
  type: SwinTransformer
  patch_size: 4
  embed_dim: 96
  depths: [2, 2, 18, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 7
head:
  nc: 2
  stride: [8.0, 16.0, 32.0]
  anchors:
    - [10,5, 18,8, 19,9]  # P3/8
    - [21,10, 25,11, 37,15]  # P4/16
    - [39,17, 49,19, 65,22]  # P5/32